year: 2020
role:
  user: 1
  admin: 2
job_per_page: 10
post_per_page: 8 
profile_per_page: 4
image_link: "https://loremflickr.com/g/300/300/logo,company/all"
logo_company: "https://png.pngtree.com/element_our/md/20180518/md_5aff6081b74c8.jpg"
validation:
  title_min: 10
  title_max: 255
  description_min: 10
  description_max: 255
  salary_min: 5
  address_min: 5
  address_max: 255
  point_length: 3
  max_length: 255
  point_less_than: 100
  point_greater_than: 0
VALID_EMAIL_REGEX: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
password_regex: !ruby/regexp /^(?=.*[a-zA-Z])(?=.*[0-9])/i
type:
  part_time: 1
  full_time: 2
rows: 10
index: 1
email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
profile:
  education_length: 250
  phone_length: 10
  email_length: 100
  address_length: 250
image:
  accept: "image/jpg, image/jpeg, image/png"
password_default : "Abc123456"
phone_number: 0123456789
notification_per_page: 6
notification_data: "notification_success"
date_setting: "%d %b. %Y"
max_notification: 5
index_number: 1
